[book]
authors = ["jzx"]
language = "cn"
multilingual = false
src = "src"
title = "搞定golang编程"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/Crtrpt/go_book"
edit-url-template = "https://github.com/Crtrpt/go_book/edit/main/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"
